services:
  web:
    image: go-discord-be:dev
    # build:
    #   context: .
    #   dockerfile: ./Dockerfile.dev
    ports:
      - 8080:8080
    # Important to bind/mount your codebase dir to /app dir for live reload
    volumes:
      - ./:/app