// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"database/sql"
)

type User struct {
	ID          int32
	DisplayName string
	AboutMe     sql.NullString
	Avatar      sql.NullString
}
